SELECT
    'ALTER ROLE "M4_USER" WITH NOSUPERUSER NOCREATEDB',
    'ALTER DATABASE M4_DATABASE OWNER TO M4_USER'
WHERE
    EXISTS (SELECT true FROM pg_roles WHERE rolname = 'M4_USER')
  AND
    EXISTS (SELECT true FROM pg_database WHERE datname = 'M4_DATABASE')
\gexec