SELECT
    'REVOKE SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public FROM "M4_USER"',
    'REVOKE USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public FROM "M4_USER"',
    'REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM "M4_USER"',
    'REVOKE CONNECT ON DATABASE M4_DATABASE FROM "M4_USER"',
    'REVOKE ALL PRIVILEGES ON DATABASE M4_DATABASE FROM "M4_USER"',
    'REVOKE ALL ON SCHEMA public FROM "M4_USER"'
WHERE
    EXISTS (SELECT true FROM pg_roles WHERE rolname = 'M4_USER')
  AND
    EXISTS (SELECT true FROM pg_database WHERE datname = 'M4_DATABASE')
\gexec