autocomplete_add cmd_family_docker_image "pg"
autocomplete_add cmd_family_docker_network "example"
autocomplete_add cmd_family_docker_service "pg"
autocomplete_add cmd_family_psql "admin" "migrator" "app"
autocomplete_add cmd_family_psql_batch "pg"
autocomplete_add cmd_family_m4_pg "pg"
autocomplete_add cmd_family_brew "pg"
autocomplete_add cmd_family_systemctl "pg"
autocomplete_add cmd_family_sqlx "tetrix_api"
autocomplete_add cmd_family_cargo_crates "sqlx"
autocomplete_add cmd_family_cargo "tetrix_package" "tetrix_workspace"
autocomplete_add cmd_family_rustup "1.86"