DT_AUTOCOMPLETIONS["methods_docker_image"]="pg"
DT_AUTOCOMPLETIONS["methods_docker_network"]="example"
DT_AUTOCOMPLETIONS["methods_docker_service"]="pg"
DT_AUTOCOMPLETIONS["methods_psql"]="admin migrator app"
DT_AUTOCOMPLETIONS["methods_psql_batch"]="pg"
DT_AUTOCOMPLETIONS["methods_m4_pg"]="pg"
DT_AUTOCOMPLETIONS["methods_brew"]="pg"
DT_AUTOCOMPLETIONS["methods_systemctl"]="pg"
