SELECT
    'GRANT USAGE ON SCHEMA public TO "M4_USER"',
    'GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO "M4_USER"',
    'GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO "M4_USER"',
    'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "M4_USER"',
    'GRANT CONNECT ON DATABASE M4_DATABASE TO "M4_USER"'
WHERE
    EXISTS (SELECT true FROM pg_roles WHERE rolname = 'M4_USER')
  AND
    EXISTS (SELECT true FROM pg_database WHERE datname = 'M4_DATABASE')
