SELECT
    'GRANT USAGE ON SCHEMA public TO "M4_USER"',
    'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "M4_USER"',
    'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "M4_USER"',
    'GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "M4_USER"',
    'GRANT CONNECT ON DATABASE M4_DATABASE TO "M4_USER"',
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "M4_USER"',
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "M4_USER"',
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO "M4_USER"'
WHERE
    EXISTS (SELECT true FROM pg_roles WHERE rolname = 'M4_USER')
  AND
    EXISTS (SELECT true FROM pg_database WHERE datname = 'M4_DATABASE')
\gexec