ALTER DATABASE template1 IS_TEMPLATE = false;
DROP DATABASE template1;
CREATE DATABASE template1 WITH OWNER = 'M4_USER' ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TEMPLATE template0;
